config/routes.rb
Rails.application.routes.draw do
  # Ruta raíz que apunta a home#index
  root 'home#index'

  # Otras rutas
  resources :tickets
  resources :orders do
      member do
    get 'summary'
      end
    collection do
      get :confirmation
      post :update_quantity
    end
    collection do
      post :create_order_and_summary
    end
    member do
      post 'finalize_sale'
    end
  end
  
    resources :products
  resources :pruebas

  get 'startup/index'
  get 'dashboard/index', to: 'dashboard#index', as: 'dashboard'
  get 'ventas/index', to: 'ventas#index', as: 'ventas'
  get 'productos/index', to: 'productos#index', as: 'productos'
  get 'predictions', to: 'predictions#index', as: 'predictions'
  scope '/predictions' do
    get 'tickets/:id/products', to: 'tickets#show_products', as: 'ticket_show_products'
  end

  scope :dashboard do
    get 'index', to: 'dashboard#index'
    post 'filter_data', to: 'dashboard#filter_data'
  end

  get 'up', to: 'rails/health#show', as: :rails_health_check
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1 class="text-center my-4">Panel de Control</h1>
<div class="row row-cols-1 row-cols-md-2 row-cols-lg-4 g-4">
  <div class="col">
  <a href="/orders" class="card text-decoration-none">
  <%= image_tag("ventas.png", class: "card-img-top", alt: "Ventas") %>
      <div class="card-body text-center">
        <h5 class="card-title">Ventas</h5>
      </div>
    </a>
  </div>
  <div class="col">
    <a href="/products" class="card text-decoration-none">
      <%= image_tag("products.png", class: "card-img-top", alt: "Productos") %>
      <div class="card-body text-center">
        <h5 class="card-title">Productos</h5>
      </div>
    </a>
  </div>
  <div class="col">
    <a href="<%= tickets_path %>" class="card text-decoration-none">
      <%= image_tag("tickes.png", class: "card-img-top", alt: "Tickets") %>
      <div class="card-body text-center">
        <h5 class="card-title">Tickets</h5>
      </div>
    </a>
  </div>
  <div class="col">
    <a href="<%= dashboard_path %>" class="card text-decoration-none">
      <%= image_tag("dash.png", class: "card-img-top", alt: "Dashboard") %>
      <div class="card-body text-center">
        <h5 class="card-title">Dashboard</h5>
      </div>
    </a>
  </div>
</div>