config/routes.rb
Rails.application.routes.draw do
  # Ruta raíz que apunta a home#index
  root 'home#index'

  # Otras rutas
  resources :tickets
  resources :orders do
      member do
    get 'summary'
      end
    collection do
      get :confirmation
      post :update_quantity
    end
    collection do
      post :create_order_and_summary
    end
    member do
      post 'finalize_sale'
    end
  end
  
    resources :products
  resources :pruebas

  get 'startup/index'
  get 'dashboard/index', to: 'dashboard#index', as: 'dashboard'
  get 'ventas/index', to: 'ventas#index', as: 'ventas'
  get 'productos/index', to: 'productos#index', as: 'productos'
  get 'predictions', to: 'predictions#index', as: 'predictions'
  scope '/predictions' do
    get 'tickets/:id/products', to: 'tickets#show_products', as: 'ticket_show_products'
  end

  scope :dashboard do
    get 'index', to: 'dashboard#index'
    post 'filter_data', to: 'dashboard#filter_data'
  end

  get 'up', to: 'rails/health#show', as: :rails_health_check
end

app/models/product.rb
class Product
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Attributes::Dynamic 

  # Campos
  field :name, type: String
  field :description, type: String
  field :inventory, type: Integer
  field :price, type: Float
  field :image, type: String 

  has_many :order_items
  # Relación con Categoría
  belongs_to :categoria, class_name: "Categoria", optional: true

  # Validaciones opcionales
  validates :name, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :inventory, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # Sop(x): frecuencia relativa del producto
  def self.sop(product_id)
    total_tickets = Ticket.total_tickets
    return 0 if total_tickets.zero?

    count = Ticket.where(product_ids: product_id).count
    (count.to_f / total_tickets).round(2)
  end

  # Sop(x U n): frecuencia relativa conjunta de dos productos
  def self.sop_union(product_id, other_product_id)
    total_tickets = Ticket.total_tickets
    return 0 if total_tickets.zero?

    count = Ticket.where(:product_ids.all => [product_id, other_product_id]).count
    (count.to_f / total_tickets).round(2)
  end

  # Número de ventas de este producto
  def sales_count
    Ticket.where(product_ids: self.id).count
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @products = Product.all
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { render :index, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :index, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    @products = Product.all
    respond_to do |format|
      if @product.update(product_params)
        format.html { render :index, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :index, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy!

    respond_to do |format|
      format.html { redirect_to products_path, status: :see_other, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :image, :inventory, :price, :categoria_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.label :inventory, style: "display: block" %>
    <%= form.number_field :inventory %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p class="fs-5">
    <strong class="text-primary">Name:</strong>
    <%= product.name %>
  </p>

  <p class="fs-5">
    <strong class="text-primary">Description:</strong>
    <%= product.description %>
  </p>

  <p class="fs-5">
    <strong class="text-primary">Image:</strong>
    <%= product.image %>
  </p>

  <p class="fs-5">
    <strong class="text-primary">Inventory:</strong>
    <%= product.inventory %>
  </p>

  <p class="fs-5">
    <strong class="text-primary">Price:</strong>
    <%= product.price %>
  </p>
</div>

app/views/products/edit.html.erb
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Editar Producto</title>
  <link rel="stylesheet" href="css/bootstrap.min.css">
  <style>
    body {
      height: 100vh;
      display: flex;
      justify-content: center;
      align-items: center;
      margin: 0;
      background-color: #f8f9fa;
    }

    .card {
      border-radius: 10px;
      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    }

    .field-spacing {
      margin-bottom: 20px;
    }

    .button-spacing {
      margin-top: 20px;
    }
  </style>
</head>
<body>

<div class="w-full my-4">
  <div class="row justify-content-center align-items-center">
    <div class="col-md-6 col-lg-8" style="width: 150rex;">
      <h1 class="text-center mb-4">Editar Producto</h1>
      <div class="card p-5 shadow-lg" style="width: 150rex;">
        <div class="card-body">
          <%= form_with model: @product, url: product_path(@product), method: :patch, local: true do |form| %>
            <div class="field-spacing">
              <%= form.label :name, 'Nombre' %>
              <%= form.text_field :name, class: "form-control" %>
            </div>
            <div class="field-spacing">
              <%= form.label :description, 'Descripción' %>
              <%= form.text_field :description, class: "form-control" %>
            </div>
            <div class="field-spacing">
              <%= form.label :image, 'Imagen' %>
              <%= form.text_field :image, class: "form-control" %>
            </div>
            <div class="field-spacing">
              <%= form.label :inventory, 'Inventario' %>
              <%= form.number_field :inventory, class: "form-control" %>
            </div>
            <div class="field-spacing">
              <%= form.label :price, 'Precio' %>
              <%= form.number_field :price, class: "form-control" %>
            </div>
            <div class="field-spacing">
              <%= form.label :categoria_id, "Categoría" %>
              <%= form.collection_select :categoria_id, Categoria.all, :id, :categoria, prompt: "Seleccione una categoría", class: "form-control" %>
            </div>

            <div class="text-center mt-4">
              <%= form.submit 'Actualizar Producto', class: 'btn btn-primary btn-lg' %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="text-center button-spacing">
        <%= link_to "Volver a productos", products_path, class: 'btn btn-secondary btn-lg' %>
      </div>
    </div>
  </div>
</div>

</body>
</html>

app/views/products/index.html.erb
<div class="container my-4">
  <p style="color: green"><%= notice %></p>

  <h1 class="text-center">Productos</h1>

  <table class="table table-striped table-bordered text-center">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Descripción</th>
        <th>Inventario</th>
        <th>Precio</th>
        <th>Categoría</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.description %></td>
          <td><%= product.inventory %></td>
          <td><%= product.price %></td>
          <td><%= product.categoria&.categoria %></td>
          <td class="d-flex justify-content-center gap-3">
              <%= link_to "Editar", edit_product_path(product), class: "btn btn-primary" %>
              <%= button_to "Eliminar", product, method: :delete, class: "btn btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="text-center">
    <%= link_to "Nuevo Producto", new_product_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/products/new.html.erb
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Nuevo Producto</title>
  <link rel="stylesheet" href="css/bootstrap.min.css">
  <style>
    body {
      height: 100vh;
      display: flex;
      justify-content: center;
      align-items: center;
      margin: 0;
      background-color: #f8f9fa;
    }

    .card {
      width: 50%; /* Ajusta el ancho del formulario */
      border-radius: 10px;
      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    }

    .field-spacing {
      margin-bottom: 20px; /* Espaciado entre campos */
    }

    .button-spacing {
      margin-top: 20px;
    }
  </style>
</head>
<body>

<div class="w-full my-4">
  <div class="row justify-content-center">
    <div class="col-md-6 col-lg-8" style="width: 150rex;">
      <h1 class="text-center mb-4">Nuevo Producto</h1>
      <div class="card p-5 shadow-lg" style="width: 150rex;">
        <div class="card-body">
          <%= form_with model: @product, url: products_path, method: :post, local: true do |form| %>
            <div class="field-spacing">
              <%= form.label :name, 'Nombre' %>
              <%= form.text_field :name, class: "form-control" %>
            </div>
            <div class="field-spacing">
              <%= form.label :description, 'Descripción' %>
              <%= form.text_field :description, class: "form-control" %>
            </div>
            <div class="field-spacing">
              <%= form.label :image, 'Imagen' %>
              <%= form.text_field :image, class: "form-control" %>
            </div>
            <div class="field-spacing">
              <%= form.label :inventory, 'Inventario' %>
              <%= form.number_field :inventory, class: "form-control" %>
            </div>
            <div class="field-spacing">
              <%= form.label :price, 'Precio' %>
              <%= form.number_field :price, class: "form-control" %>
            </div>
            <div class="field-spacing">
              <%= form.label :categoria_id, "Categoría" %>
              <%= form.collection_select :categoria_id, Categoria.all, :id, :categoria, prompt: "Seleccione una categoría", class: "form-control" %>
            </div>
            <div class="text-center mt-4">
              <%= form.submit 'Crear Producto', class: 'btn btn-primary btn-lg' %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="text-center button-spacing">
        <button class="btn btn-secondary btn-lg" onclick="window.location.href='/products'">Volver a productos</button>
      </div>
    </div>
  </div>
</div>

</body>
</html>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<div class='text-center'>
  <%= render @product %>
</div>

<div class='text-center'>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>